import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Overview",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "index",
          label: "What is Bacalhau",
        },
        {
          type: "doc",
          id: "overview/key-concepts",
          label: "Key Concepts",
        },
        {
          type: "doc",
          id: "overview/architecture",
          label: "Architecture",
        },
      ],
    },
    {
      type: "category",
      label: "Getting Started",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "getting-started/quick-start",
          label: "Quick Start",
        },
        {
          type: "doc",
          id: "getting-started/installation",
          label: "Installation",
        },
        {
          type: "doc",
          id: "getting-started/network-setup",
          label: "Network Setup",
        },
        {
          type: "category",
          label: "Basic Usage",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "getting-started/basic-usage",
            },
          ],
        },
        {
          type: "category",
          label: "Common Workflows",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "getting-started/common-workflows",
            },
          ],
        },
        {
          type: "doc",
          id: "getting-started/common-pitfalls",
          label: "Common Pitfalls",
        },
      ],
    },
  ],
  referenceSidebar: [
    { 
      type: "category",
      label: "Operators & Deployment",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Deployment Guide",
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: "autogenerated",
              dirName: "references/deployment-guide",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Developers",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "references/developers",
        },
      ],
    },
    {
      type: "category",
      label: "Help and FAQ",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "references/help-and-faq",
        },
      ],
    },
    {
      type: "category",
      label: "Setting up",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "references/setting-up",
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "references/guides",
        },
      ],
    },
  ],
  usecaseSidebar: [
    {
      type: "category",
      label: "Use Cases",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "use-cases/use-cases",
        },
      ],
    },
    {
      type: "category",
      label: "Integrations",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "use-cases/integrations",
        },
      ],
    },
  ],
  communitySidebar: [
    {
      type: "doc",
      id: "community/index",
      label: "Social Media",
    },
    {
      type: "doc",
      id: "community/community/style-guide",
      label: "Style Guide",
    },
    {
      type: "doc",
      id: "community/community/ways-to-contribute",
      label: "Ways to Contribute",
    },
    {
      type: "category",
      label: "Roadmap & Release Notes",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "community/roadmap-and-release-notes",
        },
      ],
    },
  ],
  cliapiSidebar: [
    {
      type: "category",
      label: "CLI",
      collapsible: false,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Job",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cli-api/cli/job",
            },
          ],
        },
        {
          type: "category",
          label: "Node",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cli-api/cli/node",
            },
          ],
        },
        {
          type: "category",
          label: "Agent",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cli-api/cli/agent",
            },
          ],
        },
        {
          type: "category",
          label: "Config",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cli-api/cli/config",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "API",
      items: [
        {
          type: "doc",
          id: "cli-api/api/overview",
          label: "Overview",
        },
        {
          type: "doc",
          id: "cli-api/api/jobs",
          label: "Jobs",
        },
        {
          type: "doc",
          id: "cli-api/api/agent",
          label: "Agent",
        },
        {
          type: "doc",
          id: "cli-api/api/nodes",
          label: "Nodes",
        },
      ],
    },
    {
      type: "category",
      label: "Specifications",
      items: [
        {
          type: "category",
          label: "Job Specification",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cli-api/specifications/job",
            },
          ],
        },
        {
          type: "category",
          label: "Engines",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cli-api/specifications/engines",
            },
          ],
        },
        {
          type: "category",
          label: "Publishers",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cli-api/specifications/publishers",
            },
          ],
        },
        {
          type: "category",
          label: "Sources",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cli-api/specifications/sources",
            },
          ],
        },
        {
          type: "category",
          label: "Other Specifications",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cli-api/specifications/other",
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
