import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Overview",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "index",
          label: "What is Bacalhau",
        },
        {
          type: "doc",
          id: "overview/key-concepts",
          label: "Key Concepts",
        },
        {
          type: "doc",
          id: "overview/architecture",
          label: "Architecture",
        },
      ],
    },
    {
      type: "category",
      label: "Getting Started",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "getting-started/quick-start",
          label: "Quick Start",
        },
        {
          type: "doc",
          id: "getting-started/installation",
          label: "Installation",
        },
        {
          type: "doc",
          id: "getting-started/network-setup",
          label: "Network Setup",
        },
        {
          type: "category",
          label: "Basic Usage",
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: "autogenerated",
              dirName: "getting-started/basic-usage",
            },
          ],
        },
        {
          type: "category",
          label: "Common Workflows",
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: "autogenerated",
              dirName: "getting-started/common-workflows",
            },
          ],
        },
        {
          type: "doc",
          id: "getting-started/common-pitfalls",
          label: "Common Pitfalls",
        },
      ],
    },
  ],
  referenceSidebar: [
    {
      type: "category",
      label: "Developers",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "references/developers",
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "references/guides",
        },
      ],
    },
    {
        type: "category",
        label: "Help and FAQ",
        collapsible: true,
        collapsed: false,
        items: [
          {
            type: "autogenerated",
            dirName: "references/help-and-faq",
          },
        ],
      },
      {
        type: "category",
        label: "Operations",
        collapsible: true,
        collapsed: false,
        items: [
          {
            type: "autogenerated",
            dirName: "references/operations",
          },
        ],
      },
      {
        type: "category",
        label: "Setting up",
        collapsible: true,
        collapsed: false,
        items: [
          {
            type: "autogenerated",
            dirName: "references/setting-up",
          },
        ],
      },
  ],
  usecaseSidebar: [
    {
      type: "category",
      label: "Use Cases",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "use-cases/use-cases",
        },
      ],
    },
    {
      type: "category",
      label: "Integrations",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "use-cases/integrations",
        },
      ],
    },
  ],
};

export default sidebars;