import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'index',
          label: 'What is Bacalhau',
        },
        {
          type: 'doc',
          id: 'overview/key-concepts',
          label: 'Key Concepts',
        },
        {
          type: 'doc',
          id: 'overview/architecture',
          label: 'Architecture',
        },
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'getting-started/quick-start',
          label: 'Quick Start',
        },
        {
          type: 'doc',
          id: 'getting-started/installation',
          label: 'Installation',
        },
        {
          type: 'doc',
          id: 'getting-started/network-setup',
          label: 'Network Setup',
        },
        {
          type: 'category',
          label: 'Basic Usage',
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'basic-usage',
            },
          ],
        },
        {
          type: 'category',
          label: 'Common Workflows',
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'common-workflows',
            },
          ],
        },
        {
          type: 'doc',
          id: 'common-pitfalls',
          label: 'Common Pitfalls',
        },
      ],
    },
  ],
  referenceSidebar: [
    {
      type: 'category',
      label: 'Operators & Deployment',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Deployment Guide',
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'references/deployment-guide',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Setting up',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'references/setting-up',
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer Resources',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'references/developers',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'references/guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Help and FAQ',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'references/help-and-faq',
        },
      ],
    },
  ],
  usecaseSidebar: [
    {
      type: 'category',
      label: 'Use Cases',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'use-cases/index',
      },
      items: [
        {
          type: 'doc',
          id: 'use-cases/log-processing',
          label: 'Log Processing',
        },
        {
          type: 'doc',
          id: 'use-cases/distributed-data-warehousing',
          label: 'Distributed Data Warehousing',
        },
        {
          type: 'doc',
          id: 'use-cases/fleet-management',
          label: 'Fleet Management',
        },
        {
          type: 'doc',
          id: 'use-cases/distributed-machine-learning',
          label: 'Distributed Machine Learning',
        },
        {
          type: 'doc',
          id: 'use-cases/edge-computing',
          label: 'Edge Computing',
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'integrations',
        },
      ],
    },
  ],
  communitySidebar: [
    {
      type: 'doc',
      id: 'community/index',
      label: 'Social Media',
    },
    {
      type: 'doc',
      id: 'community/community/style-guide',
      label: 'Style Guide',
    },
    {
      type: 'doc',
      id: 'community/community/ways-to-contribute',
      label: 'Ways to Contribute',
    },
    {
      type: 'category',
      label: 'Roadmap & Release Notes',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'community/roadmap-and-release-notes',
        },
      ],
    },
  ],
  cliapiSidebar: [
    {
      type: 'category',
      label: 'CLI',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'cli',
        },
      ],
    },
    {
      type: 'category',
      label: 'API',
      collapsible: false,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'api/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Specifications',
      collapsible: false,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'specifications',
        },
      ],
    },
  ],
}

export default sidebars
