export default {
  tutorialSidebar: [
    {
      type: "category",
      label: "Overview",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "index", // document ID
          label: "What is Bacalhau", // sidebar label
        },
        {
          type: "doc",
          id: "key-concepts", // document ID
          label: "Key Concepts", // sidebar label
        },
        {
          type: "doc",
          id: "architecture", // document ID
          label: "Architecture", // sidebar label
        },
      ],
    },
    {
      type: "category",
      label: "Getting Started",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "getting-started/quick-start", // document ID
          label: "Quick Start", // sidebar label
        },
        {
          type: "doc",
          id: "getting-started/installation", // document ID
          label: "Installation", // sidebar label
        },
        {
          type: "doc",
          id: "getting-started/network-setup", // document ID
          label: "Network Setup", // sidebar label
        },
        {
          type: "category",
          label: "Basic Usage",
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: "autogenerated",
              dirName: "getting-started/basic-usage", // Generate sidebar slice from docs/api
            },
          ],
        },
        {
          type: "category",
          label: "Common Workflows",
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: "autogenerated",
              dirName: "getting-started/common-workflows", // Generate sidebar slice from docs/api
            },
          ],
        },
        {
          type: "doc",
          id: "getting-started/common-pitfalls", // document ID
          label: "Common Pitfalls", // sidebar label
        },
      ],
    },
  ],
};
