import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  referencesSidebar: [
    {
      type: "category",
      label: "Developers",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "developers",
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "guides",
        },
      ],
    },
    {
        type: "category",
        label: "Help and FAQ",
        collapsible: true,
        collapsed: false,
        items: [
          {
            type: "autogenerated",
            dirName: "help-and-faq",
          },
        ],
      },
      {
        type: "category",
        label: "Operations",
        collapsible: true,
        collapsed: false,
        items: [
          {
            type: "autogenerated",
            dirName: "operations",
          },
        ],
      },
      {
        type: "category",
        label: "Setting up",
        collapsible: true,
        collapsed: false,
        items: [
          {
            type: "autogenerated",
            dirName: "setting-up",
          },
        ],
      },
  ],
};

export default sidebars;
