import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Overview',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'README',
          label: 'What is Bacalhau',
        },
        {
          type: 'autogenerated',
          dirName: 'overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
        {
          type: 'category',
          label: 'Basic Usage',
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'basics',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Feature Guides',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Components',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'components',
        },
      ],
    },
  ],
  cliApi: [
    {
      type: 'category',
      label: 'CLI',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'cli/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'cli',
        },
      ],
    },
    {
      type: 'category',
      label: 'API',
      collapsible: false,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'api/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Specifications',
      collapsible: false,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'specifications',
        },
      ],
    },
  ],
  reference: [
    {
      type: 'category',
      label: 'Operators & Deployment',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'references/operators',
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer Resources',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'references/developers',
        },
      ],
    },
    {
      type: 'category',
      label: 'Help and FAQ',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'references/help-and-faq',
        },
      ],
    },
  ],
}

export default sidebars
