import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  usecasesSidebar: [
    {
      type: "category",
      label: "Use Cases",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "use-cases",
        },
      ],
    },
    {
      type: "category",
      label: "Integrations",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "integrations",
        },
      ],
    },
  ],
};

export default sidebars;
