name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Run spell check
        run: npm run spell-check
